### ISSUE TITLE
پیشنهاد معادل

### ISSUE THREAD

**Issue by iriman** [DearRude/IranianPresets#2]
<div dir=rtl>
سلام، چند پیشنهاد برای معادل‌ها:

| واژه         | کنونی        | پیشنهاد  | توضیح                                                                                              |
|--------------|--------------|-----------|----------------------------------------------------------------------------------------------------|
| service road | دسترسی       | خدماتی    | با خیابان‌های دسترسی محلی ممکن است تداخل معنایی پیش بیاورد در حالی که این جاده‌ها معمولا highway=service نیستند       |
| restriction  | تضییق        | محدودیت   |    تضییق خیلی عربی و برایم ناآشناست                                                                                                |
| ford         | معبر آبگرفته | گدار      |                                                                 |
</div>

**Comment by DearRude** [comment]
سلام ایمان جان.
ممنون بخاطر ایشو. الساعه این‌هارو فیکس می‌کنم.
انشالله به زودی توی رلیس بعدی درست میشن.

**Comment by DearRude** [comment]
این تغییرات فیکس شد و توی ریلیز بعدی درست خواهند شد.
اما اگر می‌خوای همین‌الان داشته باشی‌شون، می‌تونی توی #جاسم لینک مستقیمی از گیت‌هاب بدی.
