### ISSUE TITLE
wrong icon

### ISSUE THREAD

**Issue by Klumbumbus** [DearRude/IranianPresets#3]
The zip file contains a file icon\OSM_Iran.svg which is used as preset main icon. However this icon has a false extension. It is a png in fact.
This causes trouble in JOSM, see https://josm.openstreetmap.de/ticket/19097

The icon extension and the code in the xml needs to be fixed.

**Comment by DearRude** [comment]
I'll fix it ASAP. Thank you for the issue!

**Comment by DearRude** [comment]
Done!
