### ISSUE TITLE
outdated icon paths

### ISSUE THREAD

**Issue by Klumbumbus** [DearRude/IranianPresets#4]
There are two outdated icon paths:
- presets/landmark/water_tower.svg -->presets/tower/water_tower.svg
- presets/landmark/tower.svg --> presets/tower/tower.svg

**Comment by DearRude** [comment]
I managed to get Github Action working that for every commit, a new release along generated zip file is created.
However, the link to latest zip file is not static and I should update it manually in JOSM presets file.

Although it can be found from something like that:
```sh
curl -s https://api.github.com/repos/DearRude/IranianPresets/releases/latest | grep 'browser_' | cut -d\" -f4
```
I'm not sure how to make a static link from that (maybe by setting a Cloudflare worker) but this would do the job

@don-vip
